version: "3.7"

networks:
    tasks:

services:
    tasks-db:
        image: postgres:12-alpine
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: tasks
            POSTGRES_DB: tasks
        volumes:
            - "./db:/var/lib/postgresql/data"
        networks:
            - tasks

    tasks-backend:
        image: python:3.8-slim
        volumes:
            - "../..:/app"
        ports:
            - "8000:8000"
        networks:
            - tasks
        depends_on:
            - tasks-db
        entrypoint: 
            - "/app/tools/run-development.sh"
    tasks-frontend:
        image: node:14-alpine
        volumes:
            - "../..:/app"
        working_dir: /app
        entrypoint: 
            - "/app/tools/run-frontend.sh"
