# Generated by Django 3.2.16 on 2023-01-10 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_auto_20230108_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='date_closed',
            field=models.DateField(blank=True, help_text='Optional – set this date whenever you feel the work on this observation is complete.', null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='pub_date',
            field=models.DateField(verbose_name='Observation date'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='type',
            field=models.ForeignKey(help_text='What type of observation is it?', on_delete=django.db.models.deletion.CASCADE, to='tree.observationtype'),
        ),
        migrations.AlterField(
            model_name='update',
            name='comment',
            field=models.TextField(verbose_name='Update'),
        ),
    ]
