# Generated by Django 3.2.16 on 2023-02-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_auto_20230110_0021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ('pk',)},
        ),
    ]
