# Generated by Django 3.2.16 on 2023-01-06 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0015_auto_20230106_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='uuid',
            new_name='id',
        ),
    ]
