# Generated by Django 3.2.16 on 2023-01-06 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0017_remove_observation_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='thread',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tree.thread'),
            preserve_default=False,
        ),
    ]
