# Generated by Django 3.2.16 on 2023-01-08 17:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0019_observation_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='id',
        ),
        migrations.AlterField(
            model_name='observation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
