# Generated by Django 3.2.16 on 2023-01-08 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0020_auto_20230108_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='uuid',
            new_name='id',
        ),
    ]
