# Generated by Django 3.2.16 on 2023-01-08 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0021_rename_uuid_observation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='observation',
        ),
    ]
