# Generated by Django 3.2.16 on 2023-01-08 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0022_remove_update_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='observation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tree.observation'),
            preserve_default=False,
        ),
    ]
