# Generated by Django 3.2.16 on 2023-01-08 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0023_update_observation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ('-pub_date',)},
        ),
    ]
